services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: los-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: los_user
      POSTGRES_PASSWORD: los_password
      POSTGRES_DB: los_db
    ports:
      - "5433:5432"
    volumes:
      - cf8deac34eb6e09cf25eca4a57ed77a50d1b4cf16940301b75c20bb8fd081181:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: los-keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  cf8deac34eb6e09cf25eca4a57ed77a50d1b4cf16940301b75c20bb8fd081181:
    external: true